id = "NODEJS-HOSTHEADER-001"
name = "Node.js Host Header Injection in Password Reset"
type = "HOST_HEADER_INJECTION"
language = "NODEJS"
regex = "req\\.headers\\.host"
file_path = "*pass*"
description = "Node.js code that uses the Host header in password reset functionality"
severity = "high"
cwe = "CWE-640"
