[github]
token = "your-github-token"
api_endpoint = "https://api.github.com"
timeout_seconds = 60
rate_limit_per_hour = 5000

patterns_dir = "configs/patterns"
output_dir = "reports"
max_results = 100
